# -*- coding: utf-8 -*-
"""BaiTapTrenLop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rlbpnEb6N25ccaux2bHcWlEEYB8YPikb
"""

import heapq

GOAL = tuple(range(1, 16)) + (0,)

# Heuristic Manhattan
def manhattan(state):
    distance = 0
    for i in range(16):
        if state[i] == 0:
            continue
        x1, y1 = divmod(i, 4)
        x2, y2 = divmod(state[i] - 1, 4)
        distance += abs(x1 - x2) + abs(y1 - y2)
    return distance

# Sinh trạng thái
def get_neighbors(state):
    neighbors = []
    idx = state.index(0)
    x, y = divmod(idx, 4)

    moves = [(-1,0),(1,0),(0,-1),(0,1)]
    for dx, dy in moves:
        nx, ny = x + dx, y + dy
        if 0 <= nx < 4 and 0 <= ny < 4:
            new_idx = nx * 4 + ny
            new_state = list(state)
            new_state[idx], new_state[new_idx] = new_state[new_idx], new_state[idx]
            neighbors.append(tuple(new_state))
    return neighbors

# AKT = Greedy
def greedy(start):
    pq = []
    heapq.heappush(pq, (manhattan(start), start, []))
    visited = set()

    while pq:
        h, state, path = heapq.heappop(pq)

        if state == GOAL:
            return path + [state]

        if state in visited:
            continue
        visited.add(state)

        for neighbor in get_neighbors(state):
            heapq.heappush(pq, (
                manhattan(neighbor),
                neighbor,
                path + [state]
            ))
    return None

# Test
start = (1,2,3,4,
         5,6,7,8,
         9,10,11,12,
         13,14,0,15)

solution = greedy(start)

if solution:
    print("Số bước:", len(solution)-1)
else:
    print("Không tìm thấy")