# -*- coding: utf-8 -*-
"""BaiTapONha

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1alxICJDdo4ARcap9AYHPwqgcTHiM6cgJ
"""

import heapq

# Heuristic Manhattan tổng quát
def manhattan(state, n):
    distance = 0
    for i in range(n*n):
        if state[i] == 0:
            continue
        x1, y1 = divmod(i, n)
        x2, y2 = divmod(state[i] - 1, n)
        distance += abs(x1 - x2) + abs(y1 - y2)
    return distance

# Sinh trạng thái kế tiếp
def get_neighbors(state, n):
    neighbors = []
    idx = state.index(0)
    x, y = divmod(idx, n)

    for dx, dy in [(-1,0),(1,0),(0,-1),(0,1)]:
        nx, ny = x + dx, y + dy
        if 0 <= nx < n and 0 <= ny < n:
            new_idx = nx*n + ny
            new_state = list(state)
            new_state[idx], new_state[new_idx] = new_state[new_idx], new_state[idx]
            neighbors.append(tuple(new_state))
    return neighbors

# In bảng đẹp
def print_board(state, n):
    for i in range(0, n*n, n):
        print(state[i:i+n])
    print()

# AKT (Greedy)
def greedy(start, n):
    GOAL = tuple(range(1, n*n)) + (0,)

    pq = []
    heapq.heappush(pq, (manhattan(start, n), start, []))
    visited = set()

    while pq:
        h, state, path = heapq.heappop(pq)

        if state == GOAL:
            return path + [state]

        if state in visited:
            continue
        visited.add(state)

        for neighbor in get_neighbors(state, n):
            heapq.heappush(pq, (
                manhattan(neighbor, n),
                neighbor,
                path + [state]
            ))

    return None

# ===== TEST =====
n = 4  # đổi thành 5, 6 nếu muốn

start = (1,2,3,4,
         5,6,7,8,
         9,10,11,12,
         13,14,0,15)

solution = greedy(start, n)

if solution:
    print("Số bước:", len(solution)-1)
    for step in solution:
        print_board(step, n)
else:
    print("Không tìm thấy")