# -*- coding: utf-8 -*-
"""BaiTapTrenLop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rlbpnEb6N25ccaux2bHcWlEEYB8YPikb
"""

import heapq

# Trạng thái đích
GOAL_STATE = (1,2,3,4,
              5,6,7,8,
              9,10,11,12,
              13,14,15,0)

# Tính Manhattan distance
def manhattan(state):
    distance = 0
    for i in range(16):
        if state[i] == 0:
            continue
        x1, y1 = divmod(i, 4)
        x2, y2 = divmod(state[i] - 1, 4)
        distance += abs(x1 - x2) + abs(y1 - y2)
    return distance

# Sinh trạng thái kế tiếp
def get_neighbors(state):
    neighbors = []
    idx = state.index(0)
    x, y = divmod(idx, 4)

    moves = [(-1,0),(1,0),(0,-1),(0,1)]  # up, down, left, right

    for dx, dy in moves:
        nx, ny = x + dx, y + dy
        if 0 <= nx < 4 and 0 <= ny < 4:
            new_idx = nx * 4 + ny
            new_state = list(state)
            new_state[idx], new_state[new_idx] = new_state[new_idx], new_state[idx]
            neighbors.append(tuple(new_state))

    return neighbors

# A* Search
def a_star(start):
    pq = []
    heapq.heappush(pq, (manhattan(start), 0, start, []))

    visited = set()

    while pq:
        f, g, state, path = heapq.heappop(pq)

        if state in visited:
            continue
        visited.add(state)

        if state == GOAL_STATE:
            return path + [state]

        for neighbor in get_neighbors(state):
            if neighbor not in visited:
                heapq.heappush(pq, (
                    g + 1 + manhattan(neighbor),
                    g + 1,
                    neighbor,
                    path + [state]
                ))

    return None

# In trạng thái dạng ma trận
def print_state(state):
    for i in range(0, 16, 4):
        print(state[i:i+4])
    print()

# Ví dụ chạy
if __name__ == "__main__":
    start_state = (1,2,3,4,
                   5,6,7,8,
                   9,10,11,12,
                   13,14,0,15)

    solution = a_star(start_state)

    if solution:
        print("Số bước:", len(solution) - 1)
        for step in solution:
            print_state(step)
    else:
        print("Không tìm được lời giải")