# -*- coding: utf-8 -*-
"""BaiTapTrenLop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rlbpnEb6N25ccaux2bHcWlEEYB8YPikb
"""

import heapq

graph = {
    'A': [('B', 1), ('C', 4)],
    'B': [('D', 2), ('E', 5)],
    'C': [('F', 3)],
    'D': [],
    'E': [('F', 1)],
    'F': []
}

heuristic = {
    'A': 7,
    'B': 6,
    'C': 2,
    'D': 1,
    'E': 1,
    'F': 0
}

def astar(start, goal):
    pq = []
    heapq.heappush(pq, (heuristic[start], 0, start, []))
    visited = set()

    while pq:
        f, g, node, path = heapq.heappop(pq)

        if node == goal:
            return path + [node]

        if node in visited:
            continue
        visited.add(node)

        for neighbor, cost in graph[node]:
            heapq.heappush(pq, (
                g + cost + heuristic[neighbor],
                g + cost,
                neighbor,
                path + [node]
            ))

    return None

print(astar('A', 'F'))