# -*- coding: utf-8 -*-
"""BaiTapONha

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1alxICJDdo4ARcap9AYHPwqgcTHiM6cgJ
"""

import heapq

class NPuzzleAStar:
    def __init__(self, n, start):
        self.n = n
        self.start = tuple(start)
        self.goal = tuple(list(range(1, n*n)) + [0])

    # ================= HEURISTIC =================

    def manhattan(self, state):
        dist = 0
        for i, val in enumerate(state):
            if val == 0:
                continue
            x1, y1 = divmod(i, self.n)
            x2, y2 = divmod(val - 1, self.n)
            dist += abs(x1 - x2) + abs(y1 - y2)
        return dist

    def linear_conflict(self, state):
        conflict = 0
        n = self.n

        # Row conflict
        for row in range(n):
            for i in range(n):
                for j in range(i+1, n):
                    idx1 = row*n + i
                    idx2 = row*n + j

                    a, b = state[idx1], state[idx2]
                    if a != 0 and b != 0:
                        if (a-1)//n == row and (b-1)//n == row:
                            if a > b:
                                conflict += 2

        # Column conflict
        for col in range(n):
            for i in range(n):
                for j in range(i+1, n):
                    idx1 = i*n + col
                    idx2 = j*n + col

                    a, b = state[idx1], state[idx2]
                    if a != 0 and b != 0:
                        if (a-1)%n == col and (b-1)%n == col:
                            if a > b:
                                conflict += 2

        return conflict

    def heuristic(self, state):
        return self.manhattan(state) + self.linear_conflict(state)

    # ================= SOLVABLE =================

    def is_solvable(self):
        arr = [x for x in self.start if x != 0]
        inv = 0
        for i in range(len(arr)):
            for j in range(i+1, len(arr)):
                if arr[i] > arr[j]:
                    inv += 1

        if self.n % 2 == 1:
            return inv % 2 == 0
        else:
            pos = self.start.index(0)
            row_from_bottom = self.n - (pos // self.n)
            return (inv + row_from_bottom) % 2 == 0

    # ================= NEIGHBORS =================

    def get_neighbors(self, state):
        n = self.n
        idx = state.index(0)
        x, y = divmod(idx, n)

        moves = [(-1,0),(1,0),(0,-1),(0,1)]
        neighbors = []

        for dx, dy in moves:
            nx, ny = x + dx, y + dy
            if 0 <= nx < n and 0 <= ny < n:
                new_idx = nx*n + ny
                lst = list(state)
                lst[idx], lst[new_idx] = lst[new_idx], lst[idx]
                neighbors.append(tuple(lst))

        return neighbors

    # ================= A* =================

    def solve(self):
        if not self.is_solvable():
            return None

        open_set = []
        heapq.heappush(open_set, (self.heuristic(self.start), 0, self.start))

        came_from = {}
        g_score = {self.start: 0}

        closed_set = set()

        while open_set:
            f, g, current = heapq.heappop(open_set)

            if current in closed_set:
                continue
            closed_set.add(current)

            if current == self.goal:
                return self.reconstruct_path(came_from, current)

            for neighbor in self.get_neighbors(current):
                tentative_g = g + 1

                if neighbor in closed_set:
                    continue

                if neighbor not in g_score or tentative_g < g_score[neighbor]:
                    g_score[neighbor] = tentative_g
                    f_score = tentative_g + self.heuristic(neighbor)

                    heapq.heappush(open_set, (f_score, tentative_g, neighbor))
                    came_from[neighbor] = current

        return None

    def reconstruct_path(self, came_from, current):
        path = [current]
        while current in came_from:
            current = came_from[current]
            path.append(current)
        path.reverse()
        return path


# ================= UTIL =================

def print_state(state, n):
    for i in range(0, len(state), n):
        print(state[i:i+n])
    print()


# ================= TEST =================

if __name__ == "__main__":
    n = 4  # có thể thử n=5 nhưng phải dễ

    start = [
        1,2,3,4,
        5,6,7,8,
        9,10,11,12,
        13,14,0,15
    ]

    puzzle = NPuzzleAStar(n, start)
    solution = puzzle.solve()

    if solution:
        print("Số bước:", len(solution) - 1)
        for step in solution:
            print_state(step, n)
    else:
        print("Không giải được")