# -*- coding: utf-8 -*-
"""BaiTapONha

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1alxICJDdo4ARcap9AYHPwqgcTHiM6cgJ
"""

import heapq

# Ma trận khoảng cách (ví dụ)
dist = [
    [0, 2, 4, 1],
    [2, 0, 3, 2],
    [4, 3, 0, 5],
    [1, 2, 5, 0]
]

n = len(dist)

# Heuristic: khoảng cách nhỏ nhất còn lại (đơn giản)
def heuristic(path):
    return 0  # có thể cải tiến

def astar_delivery(start=0):
    pq = []
    heapq.heappush(pq, (0, 0, [start]))

    while pq:
        f, cost, path = heapq.heappop(pq)

        # Nếu đi hết các điểm → quay về
        if len(path) == n:
            total_cost = cost + dist[path[-1]][start]
            return path + [start], total_cost

        for i in range(n):
            if i not in path:
                new_cost = cost + dist[path[-1]][i]
                heapq.heappush(pq, (
                    new_cost + heuristic(path),
                    new_cost,
                    path + [i]
                ))

    return None

# ===== TEST =====
route, cost = astar_delivery()

print("Lộ trình:", route)
print("Tổng chi phí:", cost)