# -*- coding: utf-8 -*-
"""baitaponha_tuan1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SyCEJOvDIRP78wRHVU14pVQeYqZDZmJx
"""

def merge_arrays_with_min(arr1, arr2):
    merged_arr = []
    len1 = len(arr1)
    len2 = len(arr2)
    min_len = min(len1, len2)

    # Merge common parts by taking the minimum
    for i in range(min_len):
        merged_arr.append(min(arr1[i], arr2[i]))

    # Append remaining elements from the longer array (if any)
    if len1 > len2:
        merged_arr.extend(arr1[min_len:])
    elif len2 > len1:
        merged_arr.extend(arr2[min_len:])

    return merged_arr

# Example usage:
arr_a = [3, 9, 1, 4]
arr_b = [2, 7, 4, 3, 2, 8]

result_array = merge_arrays_with_min(arr_a, arr_b)
print(f"Mảng a: {arr_a}")
print(f"Mảng b: {arr_b}")
print(f"Mảng kết quả: {result_array}")

# Define a sample 2D array (matrix) for testing
matrix_a = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

matrix_b = [
    [1, -2, 3],
    [-4, 5, -6],
    [7, -8, 9]
]

matrix_symmetric = [
    [1, 2, 3],
    [2, 4, 5],
    [3, 5, 6]
]

matrix_not_symmetric = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix_all_even = [
    [2, 4],
    [6, 8]
]

matrix_not_all_even = [
    [1, 2],
    [3, 4]
]

matrix_diag_increasing = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix_diag_not_increasing = [
    [3, 2, 1],
    [4, 5, 6],
    [7, 8, 9]
]

matrix_antidiag_decreasing = [
    [1, 2, 9],
    [4, 8, 6],
    [7, 5, 3]
]

matrix_antidiag_not_decreasing = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print("Sample matrix_a:")
for row in matrix_a:
    print(row)

#cau a
def sum_upper_antidiagonal_triangle(matrix):
    n = len(matrix)
    if n == 0: return 0
    if not all(len(row) == n for row in matrix): raise ValueError("Matrix must be square")

    total_sum = 0
    for i in range(n):
        for j in range(n):
            # Condition for upper triangle of anti-diagonal (including anti-diagonal)
            # For anti-diagonal, i + j == n - 1
            # For upper triangle, i + j <= n - 1
            if i + j <= n - 1:
                total_sum += matrix[i][j]
    return total_sum

# Test case
print(f"Matrix_a: {matrix_a}")
sum_val = sum_upper_antidiagonal_triangle(matrix_a)
print(f"Tổng các phần tử thuộc tam giác trên của đường chéo phụ (kể cả) trong matrix_a: {sum_val}")

matrix_3x3 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
# Anti-diagonal: 3, 5, 7
# Upper triangle (including anti-diagonal): (0,0),(0,1),(0,2), (1,0),(1,1), (2,0)
# Elements: 1, 2, 3, 4, 5, 7. Sum = 22
sum_val_3x3 = sum_upper_antidiagonal_triangle(matrix_3x3)
print(f"Tổng các phần tử thuộc tam giác trên của đường chéo phụ (kể cả) trong matrix_3x3: {sum_val_3x3}")

#cau b
def convert_negatives_to_absolute(matrix):
    # Create a new matrix to store the result to avoid modifying the original in-place
    rows = len(matrix)
    if rows == 0: return []
    cols = len(matrix[0])

    new_matrix = []
    for i in range(rows):
        new_row = []
        for j in range(cols):
            new_row.append(abs(matrix[i][j]))
        new_matrix.append(new_row)
    return new_matrix

# Test case using matrix_b which contains negative values
print(f"Original matrix_b: {matrix_b}")
abs_matrix = convert_negatives_to_absolute(matrix_b)
print(f"Matrix sau khi chuyển các số âm thành trị tuyệt đối: {abs_matrix}")

#cau c
def replace_evens_with_x(matrix, x):
    rows = len(matrix)
    if rows == 0: return []
    cols = len(matrix[0])

    new_matrix = []
    for i in range(rows):
        new_row = []
        for j in range(cols):
            if matrix[i][j] % 2 == 0:
                new_row.append(x)
            else:
                new_row.append(matrix[i][j])
        new_matrix.append(new_row)
    return new_matrix

# Test case
replacement_value = 0
print(f"Original matrix_a: {matrix_a}")
replaced_matrix = replace_evens_with_x(matrix_a, replacement_value)
print(f"Matrix sau khi thay các phần tử chẵn bằng {replacement_value}: {replaced_matrix}")

#cau d
def check_all_even(matrix):
    rows = len(matrix)
    if rows == 0: return True # An empty matrix can be considered 'all even'
    cols = len(matrix[0])
    if cols == 0: return True # An empty matrix can be considered 'all even'

    for i in range(rows):
        for j in range(cols):
            if matrix[i][j] % 2 != 0: # If any element is odd
                return False
    return True

# Test cases
print(f"Matrix_all_even: {matrix_all_even}")
print(f"Matrix_all_even có toàn chẵn không? {check_all_even(matrix_all_even)}")

print(f"Matrix_not_all_even: {matrix_not_all_even}")
print(f"Matrix_not_all_even có toàn chẵn không? {check_all_even(matrix_not_all_even)}")

#cau e
def is_symmetric_matrix(matrix):
    n = len(matrix)
    if n == 0: return True # An empty matrix is symmetric
    if not all(len(row) == n for row in matrix): raise ValueError("Matrix must be square")

    for i in range(n):
        for j in range(i + 1, n): # Only check upper triangle to avoid redundant checks
            if matrix[i][j] != matrix[j][i]:
                return False
    return True

# Test cases
print(f"Matrix_symmetric: {matrix_symmetric}")
print(f"Matrix_symmetric có đối xứng không? {is_symmetric_matrix(matrix_symmetric)}")

print(f"Matrix_not_symmetric: {matrix_not_symmetric}")
print(f"Matrix_not_symmetric có đối xứng không? {is_symmetric_matrix(matrix_not_symmetric)}")

#cau f
def is_main_diagonal_increasing(matrix):
    n = len(matrix)
    if n <= 1: return True # A 0x0 or 1x1 matrix has an 'increasing' diagonal
    if not all(len(row) == n for row in matrix): raise ValueError("Matrix must be square")

    for i in range(n - 1):
        if matrix[i][i] >= matrix[i+1][i+1]: # Check for strictly increasing
            return False
    return True

# Test cases
print(f"Matrix_diag_increasing: {matrix_diag_increasing}")
print(f"Matrix_diag_increasing có đường chéo chính tăng dần không? {is_main_diagonal_increasing(matrix_diag_increasing)}")

print(f"Matrix_diag_not_increasing: {matrix_diag_not_increasing}")
print(f"Matrix_diag_not_increasing có đường chéo chính tăng dần không? {is_main_diagonal_increasing(matrix_diag_not_increasing)}")

#cau g
def print_lower_antidiagonal_triangle(matrix):
    n = len(matrix)
    if n == 0: return
    if not all(len(row) == n for row in matrix): raise ValueError("Matrix must be square")

    elements = []
    for i in range(n):
        for j in range(n):
            # Condition for lower triangle of anti-diagonal (including anti-diagonal)
            # For anti-diagonal, i + j == n - 1
            # For lower triangle, i + j >= n - 1
            if i + j >= n - 1:
                elements.append(matrix[i][j])
    print(f"Các phần tử thuộc tam giác dưới của đường chéo phụ (kể cả): {elements}")

# Test case
print(f"Matrix_a: {matrix_a}")
print_lower_antidiagonal_triangle(matrix_a)

matrix_3x3 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
# Anti-diagonal: 3, 5, 7
# Lower triangle (including anti-diagonal): (0,2), (1,1),(1,2), (2,0),(2,1),(2,2)
# Elements: 3, 5, 6, 7, 8, 9
print(f"Matrix_3x3: {matrix_3x3}")

#cau h
def is_anti_diagonal_decreasing(matrix):
    n = len(matrix)
    if n <= 1: return True # A 0x0 or 1x1 matrix has a 'decreasing' anti-diagonal
    if not all(len(row) == n for row in matrix): raise ValueError("Matrix must be square")

    # Extract anti-diagonal elements
    anti_diagonal = [matrix[i][n - 1 - i] for i in range(n)]

    # Check if the anti-diagonal is strictly decreasing
    for i in range(len(anti_diagonal) - 1):
        if anti_diagonal[i] <= anti_diagonal[i+1]:
            return False
    return True

# Test cases
print(f"Matrix_antidiag_decreasing: {matrix_antidiag_decreasing}")
print(f"Matrix_antidiag_decreasing có đường chéo phụ giảm dần không? {is_anti_diagonal_decreasing(matrix_antidiag_decreasing)}")

print(f"Matrix_antidiag_not_decreasing: {matrix_antidiag_not_decreasing}")
print(f"Matrix_antidiag_not_decreasing có đường chéo phụ giảm dần không? {is_anti_diagonal_decreasing(matrix_antidiag_not_decreasing)}")

#cau 3
# Create three sample dictionaries
dict1 = {"name": "Alice", "age": 30}
dict2 = {"city": "New York", "population": "8.4 million"}
dict3 = {"occupation": "Engineer", "company": "Tech Corp"}

# Create a main dictionary containing the three dictionaries
main_dict = {
    "user_info": dict1,
    "location_data": dict2,
    "job_details": dict3
}

# Print the main dictionary to see its structure
print("Main dictionary containing three sub-dictionaries:")
print(main_dict)

# You can also access elements like this:
print(f"\nAlice's age: {main_dict['user_info']['age']}")
print(f"New York's population: {main_dict['location_data']['population']}")

#cau 4
# Tên file mà chúng ta sẽ tạo và ghi dữ liệu vào
file_name = "my_sample_file.txt"

# Mở file ở chế độ 'w' (write - ghi). Nếu file không tồn tại, nó sẽ được tạo mới.
# Nếu file đã tồn tại, nội dung cũ của file sẽ bị xóa và ghi đè.
# 'with' statement đảm bảo rằng file sẽ tự động được đóng sau khi hoàn thành.
with open(file_name, 'w', encoding='utf-8') as file:
    file.write("Đây là dòng đầu tiên.\n")
    file.write("Đây là dòng thứ hai với một số thông tin.\n")
    file.write("Và đây là dòng cuối cùng.")

print(f"Đã ghi dữ liệu vào file '{file_name}' thành công.")